name: gww_anomalies
channels:
  - conda-forge
  - default
dependencies:
  - python=3.12
  - pip
  - geopandas
  - fastparquet
  - pip:
      - google-cloud-storage
      - tqdm
      - ruptures
